### ISSUE TITLE
Just to be sure

### ISSUE THREAD

**Issue by Mlopezjo** [amalfra/GiantBomb#5]
Hi !
If I make `$gb_obj = new GiantBomb('YOUR_KEY');`
I can call a game list with `$gb_obj->games();`
And put all my params in `games();`

**Comment by Mlopezjo** [comment]
I've got a little probleme to install
```
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested PHP extension ext-redis * is missing from your system. Install or enable PHP's redis extension.
  Problem 2
    - Installation request for giantbomb/giantbomb ^2.0 -> satisfiable by giantbomb/giantbomb[v2.0.0].
    - giantbomb/giantbomb v2.0.0 requires ext-redis * -> the requested PHP extension redis is missing from your system.

  To enable extensions, verify that they are enabled in your .ini files:
    - C:\wamp64\bin\php\php7.3.5\php.ini
  You can also run `php --ini` inside terminal to see which files are used by PHP in CLI mode.
```

**Comment by amalfra** [comment]
@Mlopezjo it's because PHP's Redis extension is not installed. 

https://github.com/phpredis/phpredis/blob/develop/INSTALL.markdown - this is a documentation on how to install it.
If you are using ubuntu then run the following command - ```sudo apt-get install php7.x.x-redis``` where x.x is your PHP version. for eg if you are using PHP v7.4.3 then run ```sudo apt-get install php7.4.3-redis```.

Hopefully, that should fix your issue. I am closing this issue and feel free to open it if it still doesn't work.
